
[tool.pytest.ini_options]
addopts = "--color=yes"
markers = [
  "foo: marks tests are skipped when calculating the coverage",
  "slow: marks tests as slow (deselect with '-m \"not slow\"')",
  "integration: marks tests are related to integration",
]
