run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches:
      - TestMac-ci
  workflow_dispatch:

jobs:
  tests-mac:
    runs-on: macos-latest

    steps:
    - name: Install
      run: |
        brew ls

    - name: Scheduled tests
      run: |
        brew update && brew upgrade

