name: mac-tests

on:
  push:
    branches:
      - TestMac-ci
  workflow_dispatch:

jobs:
  tests-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Setup cache
      uses: actions/cache@v3
      env:
        cache-name: test
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-3.8-${{ env.cache-name }}-${{ hashFiles('**/pyproject.toml') }}-v1
        restore-keys: |
          ${{ runner.os }}-3.8-${{ env.cache-name }}-${{ hashFiles('**/pyproject.toml') }}

    - name: Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest

    - name: Scheduled tests
      run: |
        pytest -s tests
