on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests-mac:
    runs-on: macos-latest

    steps:
      - name: List homebrew
        run: |
          brew install foofoo || true
        continue-on-error: true

      - name: Update test
        run: |
          test

      - name: Install llvm
        run: |
          brew install llvm

