on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
    runs-on: macos-latest
    steps:
      - name: Install llvm
        run: |
          echo "foo" > test.txt

  second_job:
    runs-on: macos-latest
    needs: install
    steps:
      - name: cat
        run: |
          cat ./test.txt




