on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests-mac:
    runs-on: macos-latest

    steps:
      - name: List homebrew
        run: |
          brew ls

      - name: Update test
        run: |
          brew update
          brew unlink node@18 || echo "nod@18 no such keg"
          brew unlink python@3.11 || echo "python@3.11 no such keg"

          brewu install node@18 --force
          brewu install python@3.11 --force
          brew upgrade

      - name: Install llvm
        run: |
          brew install llvm

