on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests-mac:
    runs-on: macos-latest

    steps:
      - name: List homebrew
        run: |
          brew ls

      - name: Update test
        run: |
          brew update
          brew unlink node@18 || echo "nod@18 no such keg"
          brew unlink python@3.11 || echo "python@3.11 no such keg"
          brew upgrade

          rm /usr/local/bin/2to3
          brew install llvm
        env:
          HOMEBREW_VERBOSE: 1

