on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests-mac:
    runs-on: macos-latest

    steps:
      - name: List homebrew
        run: |
          brew ls

      - name: Update test
        run: |
          brew update
          brew unlink node@18
          brew unlink python@3.11
          brew upgrade
        env:
          HOMEBREW_VERBOSE: 1

