name: windows-tests

on:
  push:
    branches:
      - win_matplotlib_ci
  pull_request:
    paths:
      - '.github/workflows/windows-tests.yml'
jobs:
  tests-windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
      max-parallel: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        python3 -m pip install matplotlib pytest

    - name: Tests
      if:  ${{ github.event_name != 'schedule' }}
      run: |
        pytest

