on:
  workflow_dispatch:
    inputs:
      msg1:
        description: 'Message1'
        required: false
        type: string
      msg2:
        description: 'Message2'
        required: false
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: |
          $( test "${{ inputs.msg1 }}" && test ${{ inputs.msg2 }} ) \
             && echo "${{ inputs.msg1 }} ${{ inputs.msg2 }}" \
             || echo "foo"
